##  kubectl delete service kube-test-service | kubectl delete deployment kube-test-deployment
##  kubectl create -f kube-test.yml


apiVersion: v1
kind: Service
metadata:
  name: k8s-test-service1
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30001
    targetPort: 3000
  selector:
    app: kube-test-ms1
    
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-test-service2
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30002
    targetPort: 3000
  selector:
    app: kube-test-ms2 
    
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kube-test-deployment1
spec:
  selector:
    matchLabels:
      app: kube-test-ms1
  strategy:
    type: Recreate
  template:
    metadata:
      name: kube-test-pod1
      labels:
        app: kube-test-ms1
    spec:
      containers:
      - image: 10.39.101.226:5000/k8s-test:1.0
        name: kube-test-ms1
        ports:
        - containerPort: 3000       
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kube-test-deployment2
spec:
  selector:
    matchLabels:
      app: kube-test-ms2
  strategy:
    type: Recreate
  template:
    metadata:
      name: kube-test-pod2
      labels:
        app: kube-test-ms2
    spec:
      containers:
      - image: 10.39.101.226:5000/k8s-test:1.0
        name: kube-test-ms2
        ports:
        - containerPort: 3000       
